import React, { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Stack } from 'expo-router';

import { useResponsive } from '@/hooks/use-responsive';
import { useTheme } from '@/src/context/ThemeContext';

const PRIVACY_POLICY_TEXT = `ProFee (“the App”) is a professional fee statement and calculation tool designed for real estate agents and brokers. Your privacy is important. This Privacy Policy explains what information the App does and does not collect, and how information is handled.

Information We Collect  
Information You Enter  

ProFee allows you to enter information such as:  

Property addresses  
Sale prices and commission percentages  
Team split information  
Referral details  
Fuel proration values  

This information is entered by you and is used solely to perform calculations and generate documents.

How Information Is Stored  

All data entered into ProFee is stored locally on your device only  
ProFee does not use cloud storage  
ProFee does not transmit your data to any servers  
ProFee does not share your data with third parties  

If you delete the app, locally stored data is removed with it.

Data We Do Not Collect  

ProFee does not:  

Require user accounts or logins  
Collect names, emails, phone numbers, or contacts automatically  
Track users across apps or websites  
Use advertising identifiers  
Sell or share personal data  
Collect precise location data  

Third-Party Services  

ProFee uses standard system frameworks and libraries provided by Apple and Expo to operate properly. These services are used only to enable core app functionality and do not involve data tracking or advertising.

Analytics and Tracking  

ProFee does not use third-party analytics, advertising SDKs, or tracking technologies.

Document Generation  

Documents generated by ProFee (such as PDFs) are created on your device. You control how and where those documents are saved, shared, or sent.

Children’s Privacy  

ProFee is not intended for use by children under the age of 13 and does not knowingly collect personal information from children.

Changes to This Policy  

This Privacy Policy may be updated from time to time. Any updates will be reflected by the “Last updated” date above.

Contact  

If you have questions about this Privacy Policy, you may contact the developer at the support contact listed on the App Store page.

--------------------------------------------------`;

function splitIntoParagraphs(text: string): string[] {
  return text
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/g)
    .filter((p) => p.trim().length > 0);
}

function LegalText({ text, color }: { text: string; color: string }) {
  const paragraphs = useMemo(() => splitIntoParagraphs(text), [text]);
  return (
    <View>
      {paragraphs.map((paragraph, idx) => (
        <Text key={idx} style={{ color, fontSize: 14, lineHeight: 20, marginBottom: 12 }}>
          {paragraph}
        </Text>
      ))}
    </View>
  );
}

export default function PrivacyPolicyScreen() {
  const { theme } = useTheme();
  const responsive = useResponsive();

  const styles = StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.colors.bgPrimary,
    },
    container: {
      padding: responsive.horizontalPadding,
      paddingBottom: 28,
      alignSelf: "center",
      width: "100%",
      maxWidth: responsive.contentMaxWidth,
    },
    section: {
      backgroundColor: theme.colors.bgSecondary,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 16,
    },
    lastUpdated: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      marginBottom: 12,
    },
  });

  return (
    <View style={styles.screen}>
      <Stack.Screen options={{ title: 'Privacy Policy' }} />
      <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
        <View style={styles.section}>
          <Text style={styles.lastUpdated}>Last updated: January 4, 2026</Text>
          <LegalText text={PRIVACY_POLICY_TEXT} color={theme.colors.textPrimary} />
        </View>
      </ScrollView>
    </View>
  );
}
