import React, { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Stack } from 'expo-router';

import { useResponsive } from '@/hooks/use-responsive';
import { useTheme } from '@/src/context/ThemeContext';

const TERMS_OF_SERVICE_TEXT = `ProFee – Terms of Service  

Last updated: January 2026  

Acceptance of Terms  

By downloading or using ProFee (“the App”), you agree to these Terms of Service. If you do not agree, do not use the App.

Purpose of the App  

ProFee is a calculation and document-generation tool intended to assist real estate professionals in preparing commission statements, disbursement summaries, and related calculations.

No Professional Advice  

ProFee:  

Does not provide legal advice  
Does not provide tax advice  
Does not provide brokerage, accounting, or compliance advice  

All calculations and documents generated by the App are estimates only and are provided for convenience. Actual transaction figures may vary based on contracts, brokerage policies, lender requirements, title company practices, and applicable laws.

You are solely responsible for verifying all information before use.

Accuracy of Information  

While ProFee is designed to perform calculations accurately based on the data you enter:  

The App relies entirely on user-provided inputs  
Errors in input will result in incorrect outputs  
The developer makes no guarantees regarding completeness or accuracy  

Use of the App is at your own risk.

User Responsibility  

You agree that:  

You are responsible for all data you enter  
You will review all generated documents before sharing or relying on them  
You will comply with all applicable laws, brokerage rules, and professional obligations  

Data Storage  

All data is stored locally on your device. You are responsible for backing up or exporting documents you wish to retain.

Limitation of Liability  

To the fullest extent permitted by law, the developer of ProFee shall not be liable for:  

Financial losses  
Transaction errors  
Missed deadlines  
Incorrect disbursements  
Reliance on generated documents  

Availability  

The App is provided “as is” and “as available.” The developer does not guarantee uninterrupted availability or future feature updates.

Changes to the Terms  

These Terms may be updated periodically. Continued use of the App after changes are posted constitutes acceptance of the updated Terms.

Governing Law  

These Terms are governed by the laws of the United States, without regard to conflict-of-law principles.

Contact  

For questions or support, contact information is provided on the App Store listing.

--------------------------------------------------`;

function splitIntoParagraphs(text: string): string[] {
  return text
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/g)
    .filter((p) => p.trim().length > 0);
}

function LegalText({ text, color }: { text: string; color: string }) {
  const paragraphs = useMemo(() => splitIntoParagraphs(text), [text]);
  return (
    <View>
      {paragraphs.map((paragraph, idx) => (
        <Text key={idx} style={{ color, fontSize: 14, lineHeight: 20, marginBottom: 12 }}>
          {paragraph}
        </Text>
      ))}
    </View>
  );
}

export default function TermsOfServiceScreen() {
  const { theme } = useTheme();
  const responsive = useResponsive();

  const styles = StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.colors.bgPrimary,
    },
    container: {
      padding: responsive.horizontalPadding,
      paddingBottom: 28,
      alignSelf: "center",
      width: "100%",
      maxWidth: responsive.contentMaxWidth,
    },
    section: {
      backgroundColor: theme.colors.bgSecondary,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 16,
    },
  });

  return (
    <View style={styles.screen}>
      <Stack.Screen options={{ title: 'Terms of Service' }} />
      <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
        <View style={styles.section}>
          <LegalText text={TERMS_OF_SERVICE_TEXT} color={theme.colors.textPrimary} />
        </View>
      </ScrollView>
    </View>
  );
}
