import type { FuelProrationSummary } from "./buildFuelText";

function clampNumber(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
}

function money(value: number): string {
  return `$${value.toFixed(2)}`;
}

export function buildFuelOnlyHtml(fuel: FuelProrationSummary): string {
  const percent = Math.round(clampNumber(fuel.totalPercent, 0, 100));
  const credit = Number.isFinite(fuel.totalCredit) ? Math.max(0, fuel.totalCredit) : 0;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      background: #ffffff;
      color: #000000;
      padding: 24px;
      font-size: 12px;
    }
    h1 { font-size: 20px; margin: 0 0 12px 0; }
    .row {
      display: flex;
      justify-content: space-between;
      padding: 6px 0;
      border-bottom: 1px solid #dddddd;
    }
    .label { color: #111; }
    .value { font-weight: 600; text-align: right; }
    .disclaimer {
      margin-top: 18px;
      padding-top: 12px;
      border-top: 1px solid #dddddd;
      font-size: 10px;
      line-height: 1.35;
    }
  </style>
</head>
<body>
  <h1>Fuel Proration</h1>

  <div class="row">
    <div class="label">Fuel Level</div>
    <div class="value">${percent}%</div>
  </div>

  <div class="row">
    <div class="label">Total Fuel Credit</div>
    <div class="value">${money(credit)}</div>
  </div>

  <div class="disclaimer">
    Generated by ProFee.
  </div>
</body>
</html>`;
}
