export type FuelOnlyData = {
  totalCredit: number;
  totalPercent: number;
};

export function buildFuelEmail(fuel: FuelOnlyData): string {
  const percent = Number.isFinite(fuel.totalPercent) ? Math.round(fuel.totalPercent) : 0;
  const credit = Number.isFinite(fuel.totalCredit) ? fuel.totalCredit : 0;

  return `Fuel Proration Summary

Fuel Level: ${percent}%
Total Fuel Credit: $${credit.toFixed(2)}

Generated by ProFee`;
}
